# Generated by Django 5.0.6 on 2024-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appetizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
