# Generated by Django 5.0.6 on 2024-05-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplace', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item_price',
        ),
    ]
